In [60]:
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency

# 1. Load Dataset

In [61]:
file_path = "test-dataset.xlsx"
df = pd.read_excel(file_path)
print(f"Dataset loaded successfully! Shape: {df.shape}")

Dataset loaded successfully! Shape: (29999, 34)

In [62]:
print("Dataset Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Dataset Shape: (29999, 34)

Columns:
['Unnamed: 0', 'household_id', 'total_income', 'union_name', 'user_id', 'profile_name', 'father_name', 'mother_name', 'birthday', 'age', 'gender', 'is_poor', 'is_freedom_fighter', 'had_stroke', 'has_cardiovascular_disease', 'disabilities_name', 'diabetic', 'profile_hypertensive', 'SYSTOLIC', 'DIASTOLIC', 'RESULT_STAT_BP', 'HEIGHT', 'WEIGHT', 'BMI', 'RESULT_STAT_BMI', 'SUGAR', 'TAG_NAME', 'RESULT_STAT_SUGAR', 'PULSE_RATE', 'RESULT_STAT_PR', 'SPO2', 'RESULT_STAT_SPO2', 'MUAC', 'RESULT_STAT_MUAC']

In [63]:
df.head(10)

,Unnamed: 0,household_id,total_income,union_name,user_id,profile_name,father_name,mother_name,birthday,age,...,RESULT_STAT_BMI,SUGAR,TAG_NAME,RESULT_STAT_SUGAR,PULSE_RATE,RESULT_STAT_PR,SPO2,RESULT_STAT_SPO2,MUAC,RESULT_STAT_MUAC
0,1,241175,Lower class,KOLA,988794,মো: সাগরহোসেন,0.0,0.0,2001-11-05 18:00:00,19,...,NaN,NaN,NaN,NaN,96.0,Normal,97.0,Normal,NaN,NaN
1,2,241176,Lower class,KOLA,988796,মোছা:তামান্না,0.0,0.0,2000-06-18 18:00:00,20,...,NaN,NaN,NaN,NaN,89.0,Normal,NaN,NaN,NaN,NaN
2,3,241179,Lower class,KOLA,988802,শুকুরুচন্দ্র,0.0,0.0,1978-06-04 18:00:00,42,...,NaN,NaN,NaN,NaN,69.0,Normal,NaN,NaN,NaN,NaN
3,4,241180,Lower class,KOLA,988807,দিপালীরাণী,0.0,0.0,1956-02-02 18:00:00,64,...,NaN,8.72,Random,Normal,85.0,Normal,NaN,NaN,NaN,NaN
4,5,241181,Lower class,KOLA,988809,বুলবুলি,0.0,0.0,1996-12-25 18:00:00,23,...,NaN,NaN,NaN,NaN,101.0,High,NaN,NaN,NaN,NaN
5,6,241182,Lower class,KOLA,988811,সুপদ,0.0,0.0,1997-05-31 18:00:00,23,...,NaN,NaN,NaN,NaN,87.0,Normal,NaN,NaN,NaN,NaN
6,7,241182,Lower class,KOLA,988812,বিনা,0.0,0.0,1997-05-31 18:00:00,23,...,NaN,NaN,NaN,NaN,90.0,Normal,NaN,NaN,NaN,NaN
7,8,241183,Lower class,KOLA,988815,সুমিএারানী,0.0,0.0,1953-05-07 18:00:00,67,...,NaN,NaN,NaN,NaN,70.0,Normal,NaN,NaN,NaN,NaN
8,9,241184,Lower class,KOLA,988817,তিথিরাণী,0.0,0.0,2004-02-06 18:00:00,16,...,NaN,NaN,NaN,NaN,61.0,Normal,NaN,NaN,NaN,NaN
9,10,241185,Lower class,KOLA,988819,লবানু চন্দ্রমালী,0.0,0.0,1963-02-06 18:00:00,57,...,NaN,NaN,NaN,NaN,61.0,Normal,NaN,NaN,NaN,NaN

# 2. Data Cleaning and Preprocessing

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29999 entries, 0 to 29998
Data columns (total 34 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  29999 non-null  int64
 1   household_id                29999 non-null  int64
 2   total_income                29999 non-null  object
 3   union_name                  29999 non-null  object
 4   user_id                     29999 non-null  int64
 5   profile_name                29999 non-null  object
 6   father_name                 25561 non-null  object
 7   mother_name                 25547 non-null  object
 8   birthday                    29999 non-null  object
 9   age                         29999 non-null  int64
 10  gender                      29999 non-null  object
 11  is_poor                     29999 non-null  int64
 12  is_freedom_fighter          29999 non-null  int64
 13  had_stroke                  29999 non-null  int64
 14  has_cardiovascular_disease  29999 non-null  int64
 15  disabilities_name           29999 non-null  object
 16  diabetic                    29999 non-null  bool
 17  profile_hypertensive        29999 non-null  bool
 18  SYSTOLIC                    27600 non-null  float64
 19  DIASTOLIC                   27600 non-null  float64
 20  RESULT_STAT_BP              27600 non-null  object
 21  HEIGHT                      1128 non-null   float64
 22  WEIGHT                      1128 non-null   float64
 23  BMI                         1128 non-null   float64
 24  RESULT_STAT_BMI             1128 non-null   object
 25  SUGAR                       1583 non-null   float64
 26  TAG_NAME                    1583 non-null   object
 27  RESULT_STAT_SUGAR           1583 non-null   object
 28  PULSE_RATE                  27455 non-null  float64
 29  RESULT_STAT_PR              27455 non-null  object
 30  SPO2                        4345 non-null   float64
 31  RESULT_STAT_SPO2            4345 non-null   object
 32  MUAC                        74 non-null     float64
 33  RESULT_STAT_MUAC            74 non-null     object
dtypes: bool(2), float64(9), int64(8), object(15)
memory usage: 7.4+ MB

In [65]:
df.columns.values

array(['Unnamed: 0', 'household_id', 'total_income', 'union_name',
       'user_id', 'profile_name', 'father_name', 'mother_name',
       'birthday', 'age', 'gender', 'is_poor', 'is_freedom_fighter',
       'had_stroke', 'has_cardiovascular_disease', 'disabilities_name',
       'diabetic', 'profile_hypertensive', 'SYSTOLIC', 'DIASTOLIC',
       'RESULT_STAT_BP', 'HEIGHT', 'WEIGHT', 'BMI', 'RESULT_STAT_BMI',
       'SUGAR', 'TAG_NAME', 'RESULT_STAT_SUGAR', 'PULSE_RATE',
       'RESULT_STAT_PR', 'SPO2', 'RESULT_STAT_SPO2', 'MUAC',
       'RESULT_STAT_MUAC'], dtype=object)

In [66]:
df.dtypes

Unnamed: 0                      int64
household_id                    int64
total_income                   object
union_name                     object
user_id                         int64
profile_name                   object
father_name                    object
mother_name                    object
birthday                       object
age                             int64
gender                         object
is_poor                         int64
is_freedom_fighter              int64
had_stroke                      int64
has_cardiovascular_disease      int64
disabilities_name              object
diabetic                         bool
profile_hypertensive             bool
SYSTOLIC                      float64
DIASTOLIC                     float64
RESULT_STAT_BP                 object
HEIGHT                        float64
WEIGHT                        float64
BMI                           float64
RESULT_STAT_BMI                object
SUGAR                         float64
TAG_NAME                       object
RESULT_STAT_SUGAR              object
PULSE_RATE                    float64
RESULT_STAT_PR                 object
SPO2                          float64
RESULT_STAT_SPO2               object
MUAC                          float64
RESULT_STAT_MUAC               object
dtype: object

In [67]:
df.isnull().sum()

Unnamed: 0                        0
household_id                      0
total_income                      0
union_name                        0
user_id                           0
profile_name                      0
father_name                    4438
mother_name                    4452
birthday                          0
age                               0
gender                            0
is_poor                           0
is_freedom_fighter                0
had_stroke                        0
has_cardiovascular_disease        0
disabilities_name                 0
diabetic                          0
profile_hypertensive              0
SYSTOLIC                       2399
DIASTOLIC                      2399
RESULT_STAT_BP                 2399
HEIGHT                        28871
WEIGHT                        28871
BMI                           28871
RESULT_STAT_BMI               28871
SUGAR                         28416
TAG_NAME                      28416
RESULT_STAT_SUGAR             28416
PULSE_RATE                     2544
RESULT_STAT_PR                 2544
SPO2                          25654
RESULT_STAT_SPO2              25654
MUAC                          29925
RESULT_STAT_MUAC              29925
dtype: int64

In [68]:
# Remove duplicate records
df = df.drop_duplicates()
print("Dataset Shape:", df.shape)

Dataset Shape: (29999, 34)

In [69]:
df=df.drop('Unnamed: 0',axis=1)

In [70]:
df.head(5)

,household_id,total_income,union_name,user_id,profile_name,father_name,mother_name,birthday,age,gender,...,RESULT_STAT_BMI,SUGAR,TAG_NAME,RESULT_STAT_SUGAR,PULSE_RATE,RESULT_STAT_PR,SPO2,RESULT_STAT_SPO2,MUAC,RESULT_STAT_MUAC
0,241175,Lower class,KOLA,988794,মো: সাগরহোসেন,0.0,0.0,2001-11-05 18:00:00,19,Male,...,NaN,NaN,NaN,NaN,96.0,Normal,97.0,Normal,NaN,NaN
1,241176,Lower class,KOLA,988796,মোছা:তামান্না,0.0,0.0,2000-06-18 18:00:00,20,Female,...,NaN,NaN,NaN,NaN,89.0,Normal,NaN,NaN,NaN,NaN
2,241179,Lower class,KOLA,988802,শুকুরুচন্দ্র,0.0,0.0,1978-06-04 18:00:00,42,Male,...,NaN,NaN,NaN,NaN,69.0,Normal,NaN,NaN,NaN,NaN
3,241180,Lower class,KOLA,988807,দিপালীরাণী,0.0,0.0,1956-02-02 18:00:00,64,Female,...,NaN,8.72,Random,Normal,85.0,Normal,NaN,NaN,NaN,NaN
4,241181,Lower class,KOLA,988809,বুলবুলি,0.0,0.0,1996-12-25 18:00:00,23,Female,...,NaN,NaN,NaN,NaN,101.0,High,NaN,NaN,NaN,NaN

In [71]:
print("Dataset Shape:", df.shape)

Dataset Shape: (29999, 33)

In [72]:
# # Remove rows with missing values
# df = df.dropna()
# print("Dataset Shape:", df.shape)

In [73]:
#convert int64 to bool
df["had_stroke"] = df["had_stroke"].astype(bool)

In [74]:
#convert int64 to bool
df["has_cardiovascular_disease"] = df["has_cardiovascular_disease"].astype(bool)

In [75]:
#convert object to category
df["gender"] = df["gender"].astype("category")
df["RESULT_STAT_BMI"] = df["RESULT_STAT_BMI"].astype("category")
df["RESULT_STAT_SUGAR"] = df["RESULT_STAT_SUGAR"].astype("category")
df["RESULT_STAT_PR"] = df["RESULT_STAT_PR"].astype("category")
df["RESULT_STAT_SPO2"] = df["RESULT_STAT_SPO2"].astype("category")
df["RESULT_STAT_SPO2"] = df["RESULT_STAT_SPO2"].astype("category")
df["RESULT_STAT_MUAC"] = df["RESULT_STAT_MUAC"].astype("category")
df["RESULT_STAT_BP"] = df["RESULT_STAT_BP"].astype("category")

In [76]:
df.dtypes

household_id                     int64
total_income                    object
union_name                      object
user_id                          int64
profile_name                    object
father_name                     object
mother_name                     object
birthday                        object
age                              int64
gender                        category
is_poor                          int64
is_freedom_fighter               int64
had_stroke                        bool
has_cardiovascular_disease        bool
disabilities_name               object
diabetic                          bool
profile_hypertensive              bool
SYSTOLIC                       float64
DIASTOLIC                      float64
RESULT_STAT_BP                category
HEIGHT                         float64
WEIGHT                         float64
BMI                            float64
RESULT_STAT_BMI               category
SUGAR                          float64
TAG_NAME                        object
RESULT_STAT_SUGAR             category
PULSE_RATE                     float64
RESULT_STAT_PR                category
SPO2                           float64
RESULT_STAT_SPO2              category
MUAC                           float64
RESULT_STAT_MUAC              category
dtype: object

In [77]:
#Convert Numerical Variables to Categories
# Age Category to get significant association 
# Create a contingency table
# category_order = ['Young', 'Middle', 'Senior', 'Elderly']
# # Convert 'age' to a categorical variable with the specified order
# df['pathsize_Cat'] = pd.Categorical(df['age'], categories=category_order, ordered=True)
if 'age' in df.columns:
    df['Age_Group'] = pd.cut(
        df['age'],
        bins=[0, 30, 45, 60, 100],
        labels=['Young', 'Middle', 'Senior', 'Elderly']
    )

In [78]:

# df["has_cardiovascular_disease"][df["has_cardiovascular_disease"]==False].groupby(by=df["RESULT_STAT_BMI"]).count()

# 4. Function for Chi-Square Test

In [79]:
def chi_square_test(data, col1, col2):
    
    clean_data = data.dropna(subset=[col1, col2]) # drop rows where either col1 or col2 has NaN values
    # contingency_table = pd.crosstab(data[col1], data[col2])
    contingency_table = pd.crosstab(clean_data[col1], clean_data[col2])

    chi2, p, dof, expected = chi2_contingency(contingency_table)

    print("\n" + "=" * 60)
    print(f"Chi-Square Test: {col1} vs {col2}")
    print("=" * 60)

    print("\nContingency Table:")
    print(contingency_table)

    print("\nChi-Square Statistic =", round(chi2, 4))
    print("Degrees of Freedom =", dof)
    print("P-value =", p)

    if p < 0.05:
        print("Result: Significant Relationship")
    else:
        print("Result: No Significant Relationship")

    return [col1, col2, chi2, dof, p]

# 5. Select Variables (Taget vs other category) for Testing

In [80]:
results = []

tests = [

    ('diabetic', 'profile_hypertensive'),
    ('diabetic', 'has_cardiovascular_disease'),
    ('diabetic', 'had_stroke'),
    ('gender', 'had_stroke'),
    ('gender', 'profile_hypertensive'),
    ('gender', 'diabetic'),
    ('had_stroke', 'has_cardiovascular_disease'),
     # for other features check
    ('RESULT_STAT_BMI', 'had_stroke'),
    ('RESULT_STAT_BMI', 'has_cardiovascular_disease'),
    ('RESULT_STAT_BMI', 'diabetic'),
    ('RESULT_STAT_BMI', 'profile_hypertensive'),
    ('RESULT_STAT_BMI', 'diabetic'),
    ('gender', 'RESULT_STAT_BMI'),
    ('RESULT_STAT_BP', 'had_stroke'),
    ('RESULT_STAT_BP', 'has_cardiovascular_disease'),
    ('RESULT_STAT_BP', 'diabetic'),
    ('RESULT_STAT_BP', 'profile_hypertensive'),
    ('gender', 'RESULT_STAT_BP'),
    ('diabetic', 'RESULT_STAT_SUGAR'),
    ('has_cardiovascular_disease', 'RESULT_STAT_SUGAR'),
    ('had_stroke', 'RESULT_STAT_SUGAR'),
    ('gender', 'RESULT_STAT_SUGAR'),
    ('gender', 'RESULT_STAT_PR'),
    ('diabetic', 'RESULT_STAT_PR'),
    ('had_stroke', 'RESULT_STAT_PR'),
    ('has_cardiovascular_disease', 'RESULT_STAT_PR'),
    ('gender', 'RESULT_STAT_SPO2'),
    ('had_stroke', 'RESULT_STAT_SPO2'),
    ('diabetic', 'RESULT_STAT_SPO2'),
    ('has_cardiovascular_disease', 'RESULT_STAT_SPO2'),
    ('profile_hypertensive', 'RESULT_STAT_MUAC'),
    ('has_cardiovascular_disease', 'RESULT_STAT_MUAC'),
    ('diabetic', 'RESULT_STAT_MUAC'),
    ('had_stroke', 'RESULT_STAT_MUAC'),
    ('gender', 'total_income'),
    ('diabetic', 'total_income'),
    ('had_stroke', 'total_income'),
    ('has_cardiovascular_disease', 'total_income'),
    ('profile_hypertensive', 'total_income'),
    ('Age_Group', 'diabetic'),
    ('Age_Group', 'had_stroke'),
    ('Age_Group', 'has_cardiovascular_disease'),
    ('Age_Group', 'profile_hypertensive'),
    

]

In [81]:
for var1, var2 in tests:

    if var1 in df.columns and var2 in df.columns:
        result = chi_square_test(df, var1, var2)
        results.append(result)

============================================================
Chi-Square Test: diabetic vs profile_hypertensive
============================================================

Contingency Table:
profile_hypertensive  False  True
diabetic
False                 28172   1226
True                    252    349

Chi-Square Statistic = 3428.7364
Degrees of Freedom = 1
P-value = 0.0
Result: Significant Relationship

============================================================
Chi-Square Test: diabetic vs has_cardiovascular_disease
============================================================

Contingency Table:
has_cardiovascular_disease  False  True
diabetic
False                       29373     25
True                          592      9

Chi-Square Statistic = 91.6896
Degrees of Freedom = 1
P-value = 1.0139756023854963e-21
Result: Significant Relationship

============================================================
Chi-Square Test: diabetic vs had_stroke
============================================================

Contingency Table:
had_stroke  False  True
diabetic
False       29379     19
True          597      4

Chi-Square Statistic = 20.4715
Degrees of Freedom = 1
P-value = 6.052492705214137e-06
Result: Significant Relationship

============================================================
Chi-Square Test: gender vs had_stroke
============================================================

Contingency Table:
had_stroke  False  True
gender
Female      23223     13
Male         6753     10

Chi-Square Statistic = 4.6393
Degrees of Freedom = 1
P-value = 0.031247916131422193
Result: Significant Relationship

============================================================
Chi-Square Test: gender vs profile_hypertensive
============================================================

Contingency Table:
profile_hypertensive  False  True
gender
Female                21992   1244
Male                   6432    331

Chi-Square Statistic = 2.1318
Degrees of Freedom = 1
P-value = 0.1442703039218488
Result: No Significant Relationship

============================================================
Chi-Square Test: gender vs diabetic
============================================================

Contingency Table:
diabetic  False  True
gender
Female    22759    477
Male       6639    124

Chi-Square Statistic = 1.1744
Degrees of Freedom = 1
P-value = 0.2784975140725756
Result: No Significant Relationship

============================================================
Chi-Square Test: had_stroke vs has_cardiovascular_disease
============================================================

Contingency Table:
has_cardiovascular_disease  False  True
had_stroke
False                       29948     28
True                           17      6

Chi-Square Statistic = 1151.6605
Degrees of Freedom = 1
P-value = 1.9543015592452813e-252
Result: Significant Relationship

============================================================
Chi-Square Test: RESULT_STAT_BMI vs had_stroke
============================================================

Contingency Table:
had_stroke       False
RESULT_STAT_BMI
Highly Obesity      23
Morbid Obesity       9
Normal             612
Obesity            102
Overweight         223
Underweight        159

Chi-Square Statistic = 0.0
Degrees of Freedom = 0
P-value = 1.0
Result: No Significant Relationship

============================================================
Chi-Square Test: RESULT_STAT_BMI vs has_cardiovascular_disease
============================================================

Contingency Table:
has_cardiovascular_disease  False
RESULT_STAT_BMI
Highly Obesity                 23
Morbid Obesity                  9
Normal                        612
Obesity                       102
Overweight                    223
Underweight                   159

Chi-Square Statistic = 0.0
Degrees of Freedom = 0
P-value = 1.0
Result: No Significant Relationship

============================================================
Chi-Square Test: RESULT_STAT_BMI vs diabetic
============================================================

Contingency Table:
diabetic         False  True
RESULT_STAT_BMI
Highly Obesity      23      0
Morbid Obesity       9      0
Normal             608      4
Obesity            102      0
Overweight         220      3
Underweight        158      1

Chi-Square Statistic = 2.2798
Degrees of Freedom = 5
P-value = 0.8092263316089585
Result: No Significant Relationship

============================================================
Chi-Square Test: RESULT_STAT_BMI vs profile_hypertensive
============================================================

Contingency Table:
profile_hypertensive  False  True
RESULT_STAT_BMI
Highly Obesity           23      0
Morbid Obesity            9      0
Normal                  605      7
Obesity                  98      4
Overweight              215      8
Underweight             155      4

Chi-Square Statistic = 7.789
Degrees of Freedom = 5
P-value = 0.16825118002769227
Result: No Significant Relationship

============================================================
Chi-Square Test: RESULT_STAT_BMI vs diabetic
============================================================

Contingency Table:
diabetic         False  True
RESULT_STAT_BMI
Highly Obesity      23      0
Morbid Obesity       9      0
Normal             608      4
Obesity            102      0
Overweight         220      3
Underweight        158      1

Chi-Square Statistic = 2.2798
Degrees of Freedom = 5
P-value = 0.8092263316089585
Result: No Significant Relationship

============================================================
Chi-Square Test: gender vs RESULT_STAT_BMI
============================================================

Contingency Table:
RESULT_STAT_BMI  Highly Obesity  Morbid Obesity  Normal  Obesity  Overweight  \
gender
Female                       20               8     501       73         194
Male                          3               1     111       29          29

RESULT_STAT_BMI  Underweight
gender
Female                   113
Male                      46

Chi-Square Statistic = 21.9918
Degrees of Freedom = 5
P-value = 0.0005254866703871945
Result: Significant Relationship

============================================================
Chi-Square Test: RESULT_STAT_BP vs had_stroke
============================================================

Contingency Table:
had_stroke       False  True
RESULT_STAT_BP
High               545      0
Low               2704      0
Mild High         3568      6
Moderate High     1597      1
Normal           11477     13
Prehypertension   7057      2
Severe High        629      1

Chi-Square Statistic = 10.0815
Degrees of Freedom = 6
P-value = 0.12126105507073441
Result: No Significant Relationship

============================================================
Chi-Square Test: RESULT_STAT_BP vs has_cardiovascular_disease
============================================================

Contingency Table:
has_cardiovascular_disease  False  True
RESULT_STAT_BP
High                          545      0
Low                          2703      1
Mild High                    3567      7
Moderate High                1596      2
Normal                      11469     21
Prehypertension              7056      3
Severe High                   630      0

Chi-Square Statistic = 11.6674
Degrees of Freedom = 6
P-value = 0.0698132852067237
Result: No Significant Relationship

============================================================
Chi-Square Test: RESULT_STAT_BP vs diabetic
============================================================

Contingency Table:
diabetic         False  True
RESULT_STAT_BP
High               545      0
Low               2688     16
Mild High         3454    120
Moderate High     1534     64
Normal           11281    209
Prehypertension   6991     68
Severe High        610     20

Chi-Square Statistic = 159.9843
Degrees of Freedom = 6
P-value = 5.9671225957539e-32
Result: Significant Relationship

============================================================
Chi-Square Test: RESULT_STAT_BP vs profile_hypertensive
============================================================

Contingency Table:
profile_hypertensive  False  True
RESULT_STAT_BP
High                    545      0
Low                    2673     31
Mild High              3145    429
Moderate High          1353    245
Normal                10808    682
Prehypertension        7059      0
Severe High             538     92

Chi-Square Statistic = 1263.3828
Degrees of Freedom = 6
P-value = 9.146525092790428e-270
Result: Significant Relationship

============================================================
Chi-Square Test: gender vs RESULT_STAT_BP
============================================================

Contingency Table:
RESULT_STAT_BP  High   Low  Mild High  Moderate High  Normal  Prehypertension  \
gender
Female           369  2325       2616           1130    9453             5410
Male             176   379        958            468    2037             1649

RESULT_STAT_BP  Severe High
gender
Female                  440
Male                    190

Chi-Square Statistic = 386.0264
Degrees of Freedom = 6
P-value = 2.818939865027489e-80
Result: Significant Relationship

============================================================
Chi-Square Test: diabetic vs RESULT_STAT_SUGAR
============================================================

Contingency Table:
RESULT_STAT_SUGAR  DIABETIC (need confirmation)  HIGH (Borderline)  High  \
diabetic
False                                       497                  0     4
True                                          0                 39   174

RESULT_STAT_SUGAR  LOW (Hypoglycemia)  Low  Normal  PRE- DIABETIC
diabetic
False                              12    2     720            102
True                                4    0      29              0

Chi-Square Statistic = 1317.9573
Degrees of Freedom = 6
P-value = 1.403572240277228e-281
Result: Significant Relationship

============================================================
Chi-Square Test: has_cardiovascular_disease vs RESULT_STAT_SUGAR
============================================================

Contingency Table:
RESULT_STAT_SUGAR           DIABETIC (need confirmation)  HIGH (Borderline)  \
has_cardiovascular_disease
False                                                497                 39
True                                                   0                  0

RESULT_STAT_SUGAR           High  LOW (Hypoglycemia)  Low  Normal  \
has_cardiovascular_disease
False                        173                  16    2     747
True                           5                   0    0       2

RESULT_STAT_SUGAR           PRE- DIABETIC
has_cardiovascular_disease
False                                 102
True                                    0

Chi-Square Statistic = 26.0847
Degrees of Freedom = 6
P-value = 0.00021469795948713479
Result: Significant Relationship

============================================================
Chi-Square Test: had_stroke vs RESULT_STAT_SUGAR
============================================================

Contingency Table:
RESULT_STAT_SUGAR  DIABETIC (need confirmation)  HIGH (Borderline)  High  \
had_stroke
False                                       497                 39   178

RESULT_STAT_SUGAR  LOW (Hypoglycemia)  Low  Normal  PRE- DIABETIC
had_stroke
False                              16    2     749            102

Chi-Square Statistic = 0.0
Degrees of Freedom = 0
P-value = 1.0
Result: No Significant Relationship

============================================================
Chi-Square Test: gender vs RESULT_STAT_SUGAR
============================================================

Contingency Table:
RESULT_STAT_SUGAR  DIABETIC (need confirmation)  HIGH (Borderline)  High  \
gender
Female                                      351                 28   144
Male                                        146                 11    34

RESULT_STAT_SUGAR  LOW (Hypoglycemia)  Low  Normal  PRE- DIABETIC
gender
Female                             12    2     564             83
Male                                4    0     185             19

Chi-Square Statistic = 11.4076
Degrees of Freedom = 6
P-value = 0.0765672847670842
Result: No Significant Relationship

============================================================
Chi-Square Test: gender vs RESULT_STAT_PR
============================================================

Contingency Table:
RESULT_STAT_PR  High  Low  Normal
gender
Female          1851  478   19322
Male             355  336    5113

Chi-Square Statistic = 232.3977
Degrees of Freedom = 2
P-value = 3.431474104009845e-51
Result: Significant Relationship

============================================================
Chi-Square Test: diabetic vs RESULT_STAT_PR
============================================================

Contingency Table:
RESULT_STAT_PR  High  Low  Normal
diabetic
False           2153  802   24015
True              53   12     420

Chi-Square Statistic = 5.8633
Degrees of Freedom = 2
P-value = 0.05331020375839338
Result: No Significant Relationship

============================================================
Chi-Square Test: had_stroke vs RESULT_STAT_PR
============================================================

Contingency Table:
RESULT_STAT_PR  High  Low  Normal
had_stroke
False           2204  813   24415
True               2    1      20

Chi-Square Statistic = 0.1718
Degrees of Freedom = 2
P-value = 0.9176838859076647
Result: No Significant Relationship

============================================================
Chi-Square Test: has_cardiovascular_disease vs RESULT_STAT_PR
============================================================

Contingency Table:
RESULT_STAT_PR              High  Low  Normal
has_cardiovascular_disease
False                       2204  811   24407
True                           2    3      28

Chi-Square Statistic = 4.4064
Degrees of Freedom = 2
P-value = 0.11044986541598134
Result: No Significant Relationship

============================================================
Chi-Square Test: gender vs RESULT_STAT_SPO2
============================================================

Contingency Table:
RESULT_STAT_SPO2  Low  Normal  Very low
gender
Female             97    3122        74
Male               25     988        39

Chi-Square Statistic = 7.5221
Degrees of Freedom = 2
P-value = 0.023259850131684447
Result: Significant Relationship

============================================================
Chi-Square Test: had_stroke vs RESULT_STAT_SPO2
============================================================

Contingency Table:
RESULT_STAT_SPO2  Low  Normal  Very low
had_stroke
False             122    4108       113
True                0       2         0

Chi-Square Statistic = 0.1144
Degrees of Freedom = 2
P-value = 0.9444014423534797
Result: No Significant Relationship

============================================================
Chi-Square Test: diabetic vs RESULT_STAT_SPO2
============================================================

Contingency Table:
RESULT_STAT_SPO2  Low  Normal  Very low
diabetic
False             120    4040       112
True                2      70         1

Chi-Square Statistic = 0.447
Degrees of Freedom = 2
P-value = 0.7997266415750891
Result: No Significant Relationship

============================================================
Chi-Square Test: has_cardiovascular_disease vs RESULT_STAT_SPO2
============================================================

Contingency Table:
RESULT_STAT_SPO2            Low  Normal  Very low
has_cardiovascular_disease
False                       122    4105       113
True                          0       5         0

Chi-Square Statistic = 0.2862
Degrees of Freedom = 2
P-value = 0.8666598396471252
Result: No Significant Relationship

============================================================
Chi-Square Test: profile_hypertensive vs RESULT_STAT_MUAC
============================================================

Contingency Table:
RESULT_STAT_MUAC      Malnutrition  Nourished  Severe Malnutrition
profile_hypertensive
False                           16         56                    2

Chi-Square Statistic = 0.0
Degrees of Freedom = 0
P-value = 1.0
Result: No Significant Relationship

============================================================
Chi-Square Test: has_cardiovascular_disease vs RESULT_STAT_MUAC
============================================================

Contingency Table:
RESULT_STAT_MUAC            Malnutrition  Nourished  Severe Malnutrition
has_cardiovascular_disease
False                                 16         56                    2

Chi-Square Statistic = 0.0
Degrees of Freedom = 0
P-value = 1.0
Result: No Significant Relationship

============================================================
Chi-Square Test: diabetic vs RESULT_STAT_MUAC
============================================================

Contingency Table:
RESULT_STAT_MUAC  Malnutrition  Nourished  Severe Malnutrition
diabetic
False                       16         56                    2

Chi-Square Statistic = 0.0
Degrees of Freedom = 0
P-value = 1.0
Result: No Significant Relationship

============================================================
Chi-Square Test: had_stroke vs RESULT_STAT_MUAC
============================================================

Contingency Table:
RESULT_STAT_MUAC  Malnutrition  Nourished  Severe Malnutrition
had_stroke
False                       16         56                    2

Chi-Square Statistic = 0.0
Degrees of Freedom = 0
P-value = 1.0
Result: No Significant Relationship

============================================================
Chi-Square Test: gender vs total_income
============================================================

Contingency Table:
total_income  Lower class  Lower-middle class  Middle class  Upper class
gender
Female              15462                2353          4877          544
Male                 4513                 699          1385          166

Chi-Square Statistic = 1.1896
Degrees of Freedom = 3
P-value = 0.7554994204272173
Result: No Significant Relationship

============================================================
Chi-Square Test: diabetic vs total_income
============================================================

Contingency Table:
total_income  Lower class  Lower-middle class  Middle class  Upper class
diabetic
False               19631                2995          6089          683
True                  344                  57           173           27

Chi-Square Statistic = 38.4331
Degrees of Freedom = 3
P-value = 2.2884878063851514e-08
Result: Significant Relationship

============================================================
Chi-Square Test: had_stroke vs total_income
============================================================

Contingency Table:
total_income  Lower class  Lower-middle class  Middle class  Upper class
had_stroke
False               19960                3050          6256          710
True                   15                   2             6            0

Chi-Square Statistic = 0.9003
Degrees of Freedom = 3
P-value = 0.8253512675975321
Result: No Significant Relationship

============================================================
Chi-Square Test: has_cardiovascular_disease vs total_income
============================================================

Contingency Table:
total_income                Lower class  Lower-middle class  Middle class  \
has_cardiovascular_disease
False                             19958                3048          6250
True                                 17                   4            12

total_income                Upper class
has_cardiovascular_disease
False                               709
True                                  1

Chi-Square Statistic = 4.9292
Degrees of Freedom = 3
P-value = 0.17705889771973168
Result: No Significant Relationship


# 6. Save Results

In [82]:
results_df = pd.DataFrame(
    results,
    columns=[
        'Depentent_Variable_Target',
        'Indepentent_variable',
        'Chi_Square',
        'Degrees_Freedom',
        'P_Value'
    ]
)

In [83]:
results_df['Significant'] = results_df['P_Value'] < 0.05

print("\n\nSummary of Results")
print(results_df)

Summary of Results
     Depentent_Variable_Target        Indepentent_variable   Chi_Square  \
0                     diabetic        profile_hypertensive  3428.736435
1                     diabetic  has_cardiovascular_disease    91.689577
2                     diabetic                  had_stroke    20.471528
3                       gender                  had_stroke     4.639291
4                       gender        profile_hypertensive     2.131810
5                       gender                    diabetic     1.174407
6                   had_stroke  has_cardiovascular_disease  1151.660545
7              RESULT_STAT_BMI                  had_stroke     0.000000
8              RESULT_STAT_BMI  has_cardiovascular_disease     0.000000
9              RESULT_STAT_BMI                    diabetic     2.279819
10             RESULT_STAT_BMI        profile_hypertensive     7.789049
11             RESULT_STAT_BMI                    diabetic     2.279819
12                      gender             RESULT_STAT_BMI    21.991775
13              RESULT_STAT_BP                  had_stroke    10.081513
14              RESULT_STAT_BP  has_cardiovascular_disease    11.667411
15              RESULT_STAT_BP                    diabetic   159.984337
16              RESULT_STAT_BP        profile_hypertensive  1263.382844
17                      gender              RESULT_STAT_BP   386.026356
18                    diabetic           RESULT_STAT_SUGAR  1317.957321
19  has_cardiovascular_disease           RESULT_STAT_SUGAR    26.084689
20                  had_stroke           RESULT_STAT_SUGAR     0.000000
21                      gender           RESULT_STAT_SUGAR    11.407585
22                      gender              RESULT_STAT_PR   232.397700
23                    diabetic              RESULT_STAT_PR     5.863255
24                  had_stroke              RESULT_STAT_PR     0.171805
25  has_cardiovascular_disease              RESULT_STAT_PR     4.406387
26                      gender            RESULT_STAT_SPO2     7.522053
27                  had_stroke            RESULT_STAT_SPO2     0.114408
28                    diabetic            RESULT_STAT_SPO2     0.446971
29  has_cardiovascular_disease            RESULT_STAT_SPO2     0.286217
30        profile_hypertensive            RESULT_STAT_MUAC     0.000000
31  has_cardiovascular_disease            RESULT_STAT_MUAC     0.000000
32                    diabetic            RESULT_STAT_MUAC     0.000000
33                  had_stroke            RESULT_STAT_MUAC     0.000000
34                      gender                total_income     1.189601
35                    diabetic                total_income    38.433059
36                  had_stroke                total_income     0.900317
37  has_cardiovascular_disease                total_income     4.929155
38        profile_hypertensive                total_income     9.958818
39                   Age_Group                    diabetic   400.897149
40                   Age_Group                  had_stroke    21.944011
41                   Age_Group  has_cardiovascular_disease    15.391556
42                   Age_Group        profile_hypertensive  1458.858265

    Degrees_Freedom        P_Value  Significant
0                 1   0.000000e+00         True
1                 1   1.013976e-21         True
2                 1   6.052493e-06         True
3                 1   3.124792e-02         True
4                 1   1.442703e-01        False
5                 1   2.784975e-01        False
6                 1  1.954302e-252         True
7                 0   1.000000e+00        False
8                 0   1.000000e+00        False
9                 5   8.092263e-01        False
10                5   1.682512e-01        False
11                5   8.092263e-01        False
12                5   5.254867e-04         True
13                6   1.212611e-01        False
14                6   6.981329e-02        False
15                6   5.967123e-32         True
16                6  9.146525e-270         True
17                6   2.818940e-80         True
18                6  1.403572e-281         True
19                6   2.146980e-04         True
20                0   1.000000e+00        False
21                6   7.656728e-02        False
22                2   3.431474e-51         True
23                2   5.331020e-02        False
24                2   9.176839e-01        False
25                2   1.104499e-01        False
26                2   2.325985e-02         True
27                2   9.444014e-01        False
28                2   7.997266e-01        False
29                2   8.666598e-01        False
30                0   1.000000e+00        False
31                0   1.000000e+00        False
32                0   1.000000e+00        False
33                0   1.000000e+00        False
34                3   7.554994e-01        False
35                3   2.288488e-08         True
36                3   8.253513e-01        False
37                3   1.770589e-01        False
38                3   1.891946e-02         True
39                3   1.415227e-86         True
40                3   6.700448e-05         True
41                3   1.510845e-03         True
42                3   0.000000e+00         True

In [84]:
results_df.to_excel(
    "chi_square_results.xlsx",
    index=False
)
print("\nResults saved as chi_square_results.xlsx")

Results saved as chi_square_results.xlsx

In [85]:
significant_features = set()

for _, row in results_df.iterrows():

    if row['Significant']:

        significant_features.add(row['Depentent_Variable_Target'])
        significant_features.add(row['Indepentent_variable'])

print("\nStatistically Significant Features:")
print(significant_features)

Statistically Significant Features:
{'RESULT_STAT_BP', 'diabetic', 'RESULT_STAT_PR', 'total_income', 'Age_Group', 'had_stroke', 'profile_hypertensive', 'RESULT_STAT_BMI', 'RESULT_STAT_SUGAR', 'gender', 'RESULT_STAT_SPO2', 'has_cardiovascular_disease'}

# 8. Feature Ranking by Significance

In [86]:
ranked = results_df.sort_values(
    by='P_Value',
    ascending=True
)

print("\nFeature Relationships Ranked by Significance:")
print(ranked)

Feature Relationships Ranked by Significance:
     Depentent_Variable_Target        Indepentent_variable   Chi_Square  \
0                     diabetic        profile_hypertensive  3428.736435
42                   Age_Group        profile_hypertensive  1458.858265
18                    diabetic           RESULT_STAT_SUGAR  1317.957321
16              RESULT_STAT_BP        profile_hypertensive  1263.382844
6                   had_stroke  has_cardiovascular_disease  1151.660545
39                   Age_Group                    diabetic   400.897149
17                      gender              RESULT_STAT_BP   386.026356
22                      gender              RESULT_STAT_PR   232.397700
15              RESULT_STAT_BP                    diabetic   159.984337
1                     diabetic  has_cardiovascular_disease    91.689577
35                    diabetic                total_income    38.433059
2                     diabetic                  had_stroke    20.471528
40                   Age_Group                  had_stroke    21.944011
19  has_cardiovascular_disease           RESULT_STAT_SUGAR    26.084689
12                      gender             RESULT_STAT_BMI    21.991775
41                   Age_Group  has_cardiovascular_disease    15.391556
38        profile_hypertensive                total_income     9.958818
26                      gender            RESULT_STAT_SPO2     7.522053
3                       gender                  had_stroke     4.639291
23                    diabetic              RESULT_STAT_PR     5.863255
14              RESULT_STAT_BP  has_cardiovascular_disease    11.667411
21                      gender           RESULT_STAT_SUGAR    11.407585
25  has_cardiovascular_disease              RESULT_STAT_PR     4.406387
13              RESULT_STAT_BP                  had_stroke    10.081513
4                       gender        profile_hypertensive     2.131810
10             RESULT_STAT_BMI        profile_hypertensive     7.789049
37  has_cardiovascular_disease                total_income     4.929155
5                       gender                    diabetic     1.174407
34                      gender                total_income     1.189601
28                    diabetic            RESULT_STAT_SPO2     0.446971
9              RESULT_STAT_BMI                    diabetic     2.279819
11             RESULT_STAT_BMI                    diabetic     2.279819
36                  had_stroke                total_income     0.900317
29  has_cardiovascular_disease            RESULT_STAT_SPO2     0.286217
24                  had_stroke              RESULT_STAT_PR     0.171805
27                  had_stroke            RESULT_STAT_SPO2     0.114408
7              RESULT_STAT_BMI                  had_stroke     0.000000
30        profile_hypertensive            RESULT_STAT_MUAC     0.000000
20                  had_stroke           RESULT_STAT_SUGAR     0.000000
8              RESULT_STAT_BMI  has_cardiovascular_disease     0.000000
31  has_cardiovascular_disease            RESULT_STAT_MUAC     0.000000
32                    diabetic            RESULT_STAT_MUAC     0.000000
33                  had_stroke            RESULT_STAT_MUAC     0.000000

    Degrees_Freedom        P_Value  Significant
0                 1   0.000000e+00         True
42                3   0.000000e+00         True
18                6  1.403572e-281         True
16                6  9.146525e-270         True
6                 1  1.954302e-252         True
39                3   1.415227e-86         True
17                6   2.818940e-80         True
22                2   3.431474e-51         True
15                6   5.967123e-32         True
1                 1   1.013976e-21         True
35                3   2.288488e-08         True
2                 1   6.052493e-06         True
40                3   6.700448e-05         True
19                6   2.146980e-04         True
12                5   5.254867e-04         True
41                3   1.510845e-03         True
38                3   1.891946e-02         True
26                2   2.325985e-02         True
3                 1   3.124792e-02         True
23                2   5.331020e-02        False
14                6   6.981329e-02        False
21                6   7.656728e-02        False
25                2   1.104499e-01        False
13                6   1.212611e-01        False
4                 1   1.442703e-01        False
10                5   1.682512e-01        False
37                3   1.770589e-01        False
5                 1   2.784975e-01        False
34                3   7.554994e-01        False
28                2   7.997266e-01        False
9                 5   8.092263e-01        False
11                5   8.092263e-01        False
36                3   8.253513e-01        False
29                2   8.666598e-01        False
24                2   9.176839e-01        False
27                2   9.444014e-01        False
7                 0   1.000000e+00        False
30                0   1.000000e+00        False
20                0   1.000000e+00        False
8                 0   1.000000e+00        False
31                0   1.000000e+00        False
32                0   1.000000e+00        False
33                0   1.000000e+00        False